import re
import unicodedata

STOP_WORDS_FR = {
    "a",
    "au",
    "aux",
    "avec",
    "ce",
    "ces",
    "dans",
    "de",
    "des",
    "du",
    "elle",
    "en",
    "et",
    "eux",
    "il",
    "ils",
    "je",
    "la",
    "le",
    "les",
    "leur",
    "lui",
    "ma",
    "mais",
    "me",
    "même",
    "meme",
    "mes",
    "moi",
    "mon",
    "ne",
    "nos",
    "notre",
    "nous",
    "on",
    "ou",
    "par",
    "pas",
    "pour",
    "qu",
    "que",
    "qui",
    "sa",
    "se",
    "ses",
    "son",
    "sur",
    "ta",
    "te",
    "tes",
    "toi",
    "ton",
    "tu",
    "un",
    "une",
    "vos",
    "votre",
    "vous",
    "c",
    "d",
    "j",
    "l",
    "m",
    "n",
    "s",
    "t",
    "y",
    "ete",
    "été",
    "etee",
    "étée",
    "etant",
    "étant",
    "etante",
    "étante",
    "etants",
    "étants",
    "etantes",
    "étantes",
    "suis",
    "es",
    "est",
    "sommes",
    "êtes",
    "etes",
    "sont",
    "serai",
    "seras",
    "sera",
    "serons",
    "serez",
    "seront",
    "serais",
    "serait",
    "serions",
    "seriez",
    "seraient",
    "etais",
    "étais",
    "etait",
    "était",
    "etions",
    "étions",
    "etiez",
    "étiez",
    "etaient",
    "étaient",
    "fus",
    "fut",
    "fûmes",
    "fumes",
    "fûtes",
    "futes",
    "furent",
    "sois",
    "soit",
    "soyons",
    "soyez",
    "soient",
    "fusse",
    "fusses",
    "fût",
    "fussions",
    "fussiez",
    "fussent",
    "ai",
    "as",
    "avons",
    "avez",
    "ont",
    "aurai",
    "auras",
    "aura",
    "aurons",
    "aurez",
    "auront",
    "aurais",
    "aurait",
    "aurions",
    "auriez",
    "auraient",
    "avais",
    "avait",
    "avions",
    "aviez",
    "avaient",
    "eut",
    "eûmes",
    "eumes",
    "eûtes",
    "eutes",
    "eurent",
    "aie",
    "aies",
    "ait",
    "ayons",
    "ayez",
    "aient",
    "eusse",
    "eusses",
    "eût",
    "eussions",
    "eussiez",
    "eussent",
}

TEST_TEXTS = mes_textes_test = [
    # --- Intelligence Artificielle & Data Science ---
    "Introduction aux algorithmes de machine learning",
    "Comprendre le fonctionnement des réseaux de neurones artificiels",
    "Le deep learning appliqué à la reconnaissance d'images",
    "Comment entraîner un modèle de traitement du langage naturel (NLP)",
    "L'impact de l'intelligence artificielle sur le marché du travail",
    "Optimisation des hyperparamètres dans un réseau de neurones",
    "Les bases de la data science et de l'analyse de données",
    "Différence entre apprentissage supervisé et non supervisé",
    "Génération de texte avec les modèles LLM comme GPT",
    "Les biais cognitifs dans les algorithmes d'intelligence artificielle",
    "Utiliser Python et Pandas pour nettoyer un dataset",
    "Introduction à Scikit-Learn pour le machine learning",
    "Déployer un modèle d'IA en production avec Docker",
    "Les enjeux éthiques de l'intelligence artificielle",
    "Comment fonctionne l'algorithme de recommandation de Netflix",
    "Les transformers et l'architecture de base des LLM",
    "Calcul matriciel et tenseurs pour le deep learning",
    "La vision par ordinateur au service de la médecine",
    "Créer un chatbot intelligent avec des embeddings et FAISS",
    "Le futur de l'IA générative dans la création artistique",
    # --- Programmation & Développement Web ---
    "Les fondamentaux du langage JavaScript pour le web",
    "Créer une API REST performante avec Node.js",
    "Introduction au framework React pour les interfaces utilisateurs",
    "Comment optimiser le temps de chargement d'un site web",
    "Les différences entre SQL et NoSQL pour la gestion de bases de données",
    "Apprendre les bases du HTML5 et du CSS3",
    "Comprendre le concept de DOM (Document Object Model)",
    "Créer des animations CSS fluides pour le web",
    "L'architecture microservices expliquée aux débutants",
    "Sécuriser une application web contre les failles XSS",
    "Les avantages de TypeScript par rapport à JavaScript",
    "Introduction à la gestion de versions avec Git et GitHub",
    "Comment configurer un pipeline CI/CD avec GitHub Actions",
    "Le rôle du backend dans une architecture web moderne",
    "Développer une application mobile multiplateforme avec Flutter",
    "Les bonnes pratiques de l'accessibilité web (a11y)",
    "Créer un serveur web asynchrone en Python avec FastAPI",
    "L'hébergement cloud et le déploiement sur AWS",
    "Comprendre les promesses et l'asynchronisme en JavaScript",
    "Les design patterns incontournables en génie logiciel",
    # --- Pâtisserie & Desserts ---
    "La recette authentique de la tarte aux pommes",
    "Comment réussir une pâte à choux parfaite",
    "Les secrets d'un fondant au chocolat au cœur coulant",
    "Faire ses propres macarons à la framboise",
    "La technique pour un glaçage miroir sans défaut",
    "Recette de la crème pâtissière onctueuse à la vanille",
    "Préparer une brioche tressée moelleuse pour le petit-déjeuner",
    "Les astuces pour une pâte sablée qui ne s'effrite pas",
    "Recette du tiramisu italien traditionnel au café",
    "Comment monter des blancs en neige bien fermes",
    "La cuisson idéale pour des cookies croustillants et moelleux",
    "Faire une mousse au chocolat légère et aérienne",
    "Les étapes de préparation d'un mille-feuille",
    "Recette de crêpes bretonnes et de leur caramel beurre salé",
    "Astuces de chef pour réussir sa crème brûlée",
    "Le Paris-Brest et sa crème mousseline au praliné",
    "Gâteau au yaourt facile à faire avec les enfants",
    "Préparer un entremets fruits rouges pour un anniversaire",
    "Comment réaliser une meringue française brillante",
    "Recette de financiers aux amandes pour le goûter",
    # --- Cuisine Salée & Gastronomie ---
    "Recette traditionnelle du bœuf bourguignon",
    "Comment cuire un steak parfait à la poêle",
    "La préparation d'un risotto aux champignons crémeux",
    "Faire sa propre pâte à pizza maison comme en Italie",
    "Les secrets d'une blanquette de veau réussie",
    "Recette de lasagnes à la bolognaise gratinées",
    "Comment lever les filets d'un poisson frais",
    "La cuisson du magret de canard au miel et vinaigre balsamique",
    "Préparer un potage velouté au potiron pour l'hiver",
    "Recette du gratin dauphinois traditionnel",
    "Les épices indispensables pour un curry de poulet indien",
    "Faire des sushis et makis maison étape par étape",
    "Astuces pour une omelette baveuse et savoureuse",
    "La vraie recette des spaghettis à la carbonara sans crème",
    "Comment réussir la cuisson des asperges vertes",
    "Préparer une marinade savoureuse pour le barbecue",
    "Recette de la quiche lorraine avec une pâte brisée",
    "Les accords mets et vins pour un repas de fête",
    "Cuisiner un tajine d'agneau aux pruneaux",
    "Comment réaliser un bouillon de volaille maison",
    # --- Espace & Astronomie ---
    "La formation des trous noirs supermassifs au centre des galaxies",
    "L'exploration de la planète Mars par les rovers de la NASA",
    "Les exoplanètes et la recherche de vie extraterrestre",
    "Comprendre le fonctionnement des étoiles et la fusion nucléaire",
    "L'histoire de la mission Apollo 11 sur la Lune",
    "Le télescope spatial James Webb et ses premières découvertes",
    "Les anneaux de Saturne : composition et mystères",
    "La théorie du Big Bang et l'expansion de l'univers",
    "Qu'est-ce que la matière noire et l'énergie sombre ?",
    "Le cycle de vie d'une étoile : de la nébuleuse à la naine blanche",
    "Les pluies de météores et les étoiles filantes",
    "Les défis de la colonisation spatiale et des voyages interstellaires",
    "La station spatiale internationale (ISS) et la vie en apesanteur",
    "Les galaxies spirales et l'anatomie de la Voie Lactée",
    "Les quasars : les objets les plus lumineux de l'univers",
    "Comprendre les éclipses solaires et lunaires",
    "L'orbite des planètes de notre système solaire",
    "Les aurores boréales : une explication scientifique",
    "La course à l'espace entre les États-Unis et l'URSS",
    "Sondes spatiales Voyager : au-delà du système solaire",
    # --- Physique, Mathématiques & Sciences ---
    "Les principes fondamentaux de la physique quantique",
    "Le chat de Schrödinger et la superposition quantique",
    "Comprendre la théorie de la relativité générale d'Einstein",
    "Le principe d'incertitude de Heisenberg expliqué",
    "Les lois de la thermodynamique et l'entropie",
    "L'accélérateur de particules du CERN et le boson de Higgs",
    "Introduction à la mécanique des fluides",
    "Le nombre d'or et la suite de Fibonacci dans la nature",
    "La géométrie fractale et l'ensemble de Mandelbrot",
    "Les bases du calcul différentiel et intégral",
    "La théorie des cordes : une tentative d'unification",
    "Les forces fondamentales de la nature",
    "La supraconductivité à haute température",
    "L'électromagnétisme et les équations de Maxwell",
    "Les mystères des nombres premiers en cryptographie",
    "Le fonctionnement des lasers physiques",
    "La mécanique newtonienne classique",
    "La radioactivité et le principe de demi-vie",
    "Le paradoxe des jumeaux en relativité restreinte",
    "La fusion froide : mythe ou réalité de demain ?",
    # --- Sport & Fitness ---
    "Programme d'entraînement pour courir son premier marathon",
    "Les bienfaits de la musculation sur la densité osseuse",
    "Comment bien récupérer après une séance de HIIT",
    "La nutrition sportive pour la prise de masse musculaire",
    "Les étirements essentiels pour éviter les blessures en course à pied",
    "Les bases du CrossFit et ses mouvements fondamentaux",
    "Améliorer son endurance cardiovasculaire à vélo",
    "L'importance de l'hydratation pendant l'effort physique",
    "Comment exécuter parfaitement un squat avec barre",
    "Les compléments alimentaires utiles pour les sportifs",
    "La natation : un sport complet pour le dos et les articulations",
    "Prévenir les tendinites chez le sportif régulier",
    "Les bénéfices du yoga pour la mobilité et la souplesse",
    "Comment préparer mentalement une compétition sportive",
    "Les erreurs à éviter pour les débutants en salle de sport",
    "L'entraînement en fractionné (interval training) pour brûler des graisses",
    "Renforcement de la sangle abdominale et gainage",
    "Le rôle du sommeil dans la récupération musculaire",
    "Comment choisir ses chaussures de running",
    "Les principes de la surcharge progressive en musculation",
    # --- Football & Sports d'équipe ---
    "Les tactiques de jeu dans le football moderne",
    "L'histoire de la Coupe du Monde de la FIFA",
    "Comment améliorer sa conduite de balle au football",
    "Les règles de base du rugby à XV",
    "L'évolution du rôle du gardien de but au football",
    "Les systèmes de défense en zone au basket-ball",
    "Les plus grandes rivalités de l'histoire du football",
    "L'impact financier de la Ligue des Champions",
    "Le tir à trois points et la révolution de la NBA",
    "Comment tirer un coup franc parfait au foot",
    "L'arbitrage vidéo (VAR) : avantages et inconvénients",
    "Les fondamentaux du passe-et-va au basket",
    "Le rôle du capitaine dans une équipe de sport",
    "Les règles du hors-jeu expliquées simplement",
    "L'entraînement tactique d'une équipe de volley-ball",
    "Le handball et l'importance des phases de contre-attaque",
    "Le poste de demi de mêlée au rugby",
    "Le développement des jeunes talents dans les centres de formation",
    "L'importance des supporters et des ultras dans les stades",
    "Les statistiques avancées (Data Analytics) dans le sport de haut niveau",
    # --- Histoire & Antiquité ---
    "L'ascension et la chute de l'Empire Romain",
    "Les mystères de la construction des pyramides d'Égypte",
    "La vie quotidienne à Athènes dans la Grèce antique",
    "Les conquêtes d'Alexandre le Grand",
    "La révolution française de 1789 et ses conséquences",
    "La première guerre mondiale : causes et alliances",
    "La civilisation maya : culture et disparition",
    "Les samouraïs : code d'honneur et rôle dans le Japon féodal",
    "L'Empire byzantin et la chute de Constantinople",
    "La guerre froide et le mur de Berlin",
    "La mythologie nordique : dieux et croyances des Vikings",
    "Les pharaons les plus célèbres de l'Égypte antique",
    "La peste noire et son impact sur l'Europe médiévale",
    "Le système féodal au Moyen Âge",
    "La découverte de l'Amérique par Christophe Colomb",
    "L'industrialisation de l'Europe au 19ème siècle",
    "Cléopâtre : la dernière reine d'Égypte",
    "Les croisades : un conflit entre Orient et Occident",
    "La renaissance italienne : arts et découvertes",
    "L'empire mongol sous Genghis Khan",
    # --- Jardinage, Nature & Animaux ---
    "Comment créer un potager en permaculture",
    "Les meilleures plantes d'intérieur pour purifier l'air",
    "Attirer les abeilles et les pollinisateurs dans son jardin",
    "La taille des rosiers à la fin de l'hiver",
    "Composter ses déchets organiques à la maison",
    "Les bases de l'aquariophilie d'eau douce",
    "Comment cultiver des tomates charnues sur son balcon",
    "Le comportement social des loups à l'état sauvage",
    "Reconnaître les oiseaux de son jardin",
    "Les associations de cultures bénéfiques au potager",
    "L'arrosage automatique goutte à goutte pour les plantes",
    "L'intelligence étonnante des corbeaux et des pieuvres",
    "Comment lutter naturellement contre les pucerons",
    "La migration annuelle des papillons monarques",
    "Semer de la pelouse : quand et comment s'y prendre",
    "La symbiose entre les champignons mycorhiziens et les arbres",
    "Le bouturage des plantes grasses et succulentes",
    "L'impact de la déforestation sur la biodiversité mondiale",
    "Comprendre le langage corporel des chiens",
    "Créer un hôtel à insectes pour préserver la faune locale",
]


def clean_before_embedding(text):
    if not text:
        return ""

    # Remove french special chars
    replacements = {
        "ç": "c",
        "Ç": "C",
        "œ": "oe",
        "Œ": "OE",
        "æ": "ae",
        "Æ": "AE",
        "’": "'",
        "‘": "'",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    # Remove accents
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")

    # Keep letters and digits only
    text = re.sub(r"[^a-zA-Z0-9]+", " ", text)

    # Lowercase
    words = text.lower().split()

    # Remove stop words
    filtered = [w for w in words if w not in STOP_WORDS_FR and len(w) > 1]

    return " ".join(filtered)
