"""Initial schema

Revision ID: 6c3b4953ccad
Revises:
Create Date: 2026-07-09 01:38:14.659401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3b4953ccad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('pdf_file', sa.String(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('is_handwritten', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation',
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('is_anonymized', sa.Boolean(), nullable=True),
    sa.Column('is_of_interest', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('ocr', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('num_words', sa.Integer(), nullable=True),
    sa.Column('num_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contribution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('feeling')
    op.drop_table('extraction')
    op.drop_table('annotation')
    op.drop_table('contribution')
    # ### end Alembic commands ###
