services:
  vllm:
    extends:
      file: docker-compose.base.yml
      service: vllm
    container_name: qwen3.5-2b
    image: vllm/vllm-openai:v0.25.1
    command:
      - --host=0.0.0.0
      - --port=8000
      - --gpu-memory-utilization=0.8
      - --model=Qwen/Qwen3.5-2B
      - --language-model-only
      - --enable-auto-tool-choice
      - --tool-call-parser=qwen3_coder
      - --reasoning-parser=qwen3
      - --enable-prefix-caching
      - --max-model-len=16384
      - --max-num-seqs=16
