"""expand: ref_topic et colonnes instances sur topic

Revision ID: fd5a99be52e1
Revises: 6c3b4953ccad
Create Date: 2026-07-14 21:32:19.921161

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd5a99be52e1"
down_revision: str | Sequence[str] | None = "6c3b4953ccad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ref_topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("topic", sa.Column("ref_topic_id", sa.Integer(), nullable=True))
    op.add_column("topic", sa.Column("verbatim", sa.Text(), nullable=True))
    op.add_column("topic", sa.Column("summary", sa.Text(), nullable=True))
    op.create_foreign_key(
        "fk_topic_ref_topic_id", "topic", "ref_topic", ["ref_topic_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_topic_ref_topic_id", "topic", type_="foreignkey")
    op.drop_column("topic", "summary")
    op.drop_column("topic", "verbatim")
    op.drop_column("topic", "ref_topic_id")
    op.drop_table("ref_topic")
    # ### end Alembic commands ###
